//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aiala.Backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aiala.Backend.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create template, because the following tasks have been deleted:.
        /// </summary>
        public static string CannotCreateTemplateTaskDeleted {
            get {
                return ResourceManager.GetString("CannotCreateTemplateTaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete task &apos;{0}&apos;, because following templates  are using it:.
        /// </summary>
        public static string CannotDeleteTaskBecauseTemplates {
            get {
                return ResourceManager.GetString("CannotDeleteTaskBecauseTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type &apos;{0}&apos; not supported.
        /// </summary>
        public static string ContentTypeNotSupported {
            get {
                return ResourceManager.GetString("ContentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in UTC and at the start of the day.
        /// </summary>
        public static string DateMustBeUTCStartOfDay {
            get {
                return ResourceManager.GetString("DateMustBeUTCStartOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End must be after start.
        /// </summary>
        public static string EndMustBeAfterStart {
            get {
                return ResourceManager.GetString("EndMustBeAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image empty.
        /// </summary>
        public static string ImageEmpty {
            get {
                return ResourceManager.GetString("ImageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task overlaps with previous task.
        /// </summary>
        public static string TaskOverlapsWithPrevious {
            get {
                return ResourceManager.GetString("TaskOverlapsWithPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks have errors.
        /// </summary>
        public static string TasksHaveErrors {
            get {
                return ResourceManager.GetString("TasksHaveErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete tasks in the past or up to 5 minutes in the future.
        /// </summary>
        public static string TasksInPastDeleted {
            get {
                return ResourceManager.GetString("TasksInPastDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit tasks in the past or up to 5 minutes in the future.
        /// </summary>
        public static string TasksInPastEdited {
            get {
                return ResourceManager.GetString("TasksInPastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value required.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
    }
}
